replicaCount: 1

image:
  repository: lets_talk_db_service
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
   
  paths: []
  hosts:
    - chart-example.local
  tls: []
  

resources: {}
  

nodeSelector: {}

tolerations: []

affinity: {}
