replicaCount: 1

image:
  repository: lets_talk_UI
  tag: v1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: ["/"]
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
