kind: Service
apiVersion: v1
kind: Service
metadata:
  name: template
spec:
  selector:
    app: template
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: "Local"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: template:v1
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: CONFIGMAP_FILE
              value: "/usr/share/microservice/config.yaml"
          volumeMounts:
            - mountPath: /usr/share/microservice
              name: ms-config-volume
      volumes:
        - name: ms-config-volume
          configMap:
            name: template-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-configmap
data:
  
  config.yaml: |-
    ms:
      DEBUG: false
      TESTING: false
      APP_NAME: lets_talk_db_service
      APPLICATION_ROOT : /
      SQLALCHEMY_TRACK_MODIFICATIONS: true
      SECRET_KEY: "nhj78jdh98jsk0"
      DATABASE: db.sqlite3
      SQLALCHEMY_DATABASE_URI: sqlite:////microservice/database/db.sqlite3
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: template
    servicePort: 5000