pyms:
  services:
    requests:
      data: ""
    tracer:
      client: "lets_talk_backend"
      host: "localhost"
      component_name: "lets_talk_db_service"
  config:
    DEBUG: false
    TESTING: false
    APP_NAME: ss_assignment_01_lets_talk
    APPLICATION_ROOT : /
    SECRET_KEY: "gnhj78jdh98jsk0"
    service_host: http://localhost:80/
